### ISSUE TITLE
一直报错python3.5不能用吗 只能用3.6？

### ISSUE THREAD

**Issue by vinplezhang** [mailgyc/doudizhu#10]
self.db: torndb.Connection = self.application.db
           ^
提示这里出了问题  setting配置都已更改

**Comment by mailgyc** [comment]
对的，type hint 用了 self.db = self.application.db  改成这样3.5才可以

**Comment by vinplezhang** [comment]
谢谢 这个语法问题解决了  你这款游戏 目前只支持3人的模式吗

mailgyc <notifications@github.com> 于2018年8月2日周四 下午12:08写道：

**Comment by mailgyc** [comment]
不是的，三个人满了，再进的人就会进入新的房间，只不过前端目前没有选择房间的界面。
后面会加上
