### ISSUE TITLE
数据库问题

### ISSUE THREAD

**Issue by cuican008** [mailgyc/doudizhu#15]
mysql --user=root -p < schema.sql
Enter password:
ERROR 1293 (HY000) at line 5: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

- [ ]

**Comment by mailgyc** [comment]
可能是MySQL版本问题，在5.7 下面是可以的。
你可以试试 updated_date 换成下面：
updated_date TIMESTAMP DEFAULT ON UPDATE TIMESTAMP
