### ISSUE TITLE
出牌时卡住了

### ISSUE THREAD

**Issue by huang0518** [mailgyc/doudizhu#16]
![image](https://user-images.githubusercontent.com/11988184/50676637-61651580-1030-11e9-9432-3c2023573d15.png)
什么原因？ipdb是什么意思

**Comment by mailgyc** [comment]
这是断点吧，用 python3 app.py 启动

**Comment by mailgyc** [comment]
不好意思，以前有人加了 debug 的代码，没有删除干净，重新pull下就好了。
https://github.com/mailgyc/doudizhu/commit/babadddcee475596d43b173d8b02b1d5e95f0417

**Comment by mailgyc** [comment]
> 是用的python3 app.py 启动，挑战AI模式，选择出牌后界面没反应，命令行提示上图中的ipdb，进入http://m.ihouser.com/ 体验，也是这种情况，出牌后界面无反应
> ![image](https://user-images.githubusercontent.com/11988184/50763025-9fb93980-12a9-11e9-9f83-5759f22a0f73.png)
不好意思，以前有人加了 debug 的代码，没有删除干净，重新pull下就好了。
https://github.com/mailgyc/doudizhu/commit/babadddcee475596d43b173d8b02b1d5e95f0417
