### ISSUE TITLE
Can't connect to MySQL server on'localhost'

### ISSUE THREAD

**Issue by HaozhengLi** [mailgyc/doudizhu#17]
Python: 3.6.3
MySQL: 8.0.17

你好，我按教程进行操作，进入8080后输入完账号密码，点击注册按钮时，游戏界面红色字体报错：

`pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on'localhost'")`

以下是我的操作记录：

```
E:\Output\Python_output\CCP\doudizhu>net start mysql
mysql 服务正在启动 ..
mysql 服务已经启动成功。


E:\Output\Python_output\CCP\doudizhu>mysql --user=root -p < schema.sql
Enter password: *****

E:\Output\Python_output\CCP\doudizhu>cd doudizhu

E:\Output\Python_output\CCP\doudizhu\doudizhu>python app.py --password=mysql
2019-08-31 18:13 server on http://127.0.0.1:8080
```

请问如何解决，谢谢！

**Comment by HaozhengLi** [comment]
在`mysql --user=root -p < schema.sql`一步中，我输入了我设置的MySQL密码：mysql

所以在`python app.py --password=mysql`一步中，我写了`--password=mysql`请问这样写对吗？

**Comment by HaozhengLi** [comment]
查到问题了，运行命令`python app.py --password=xxxxx`中的参数$password实际上根本没有被传进程序中，

文件'doudizhu\doudizhu\contrib\db\aio_db.py'中定义的类AsyncConnection初始化时，参数列表self._db_args并没有被$password中的参数初始化，

在async def reconnect(self)函数中print一下会发现：无论用户在运行程序时给$password填什么，程序里的password都是123456，因为密码错误，所以无法使用MySQL，所以报错。

所以我在类AsyncConnection初始化时直接写死了password为我自己的密码，运行时直接`python app.py`就解决了。

**Comment by mailgyc** [comment]
密码改成在 settings/dev.py 里面配置的，文档没有跟着改

**Comment by HaozhengLi** [comment]
了解，感谢解答。
