### ISSUE TITLE
ERROR 1064 (42000) at line 15: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '{},

### ISSUE THREAD

**Issue by yuqianglianshou** [mailgyc/doudizhu#39]
你好作者，我在执行
  mysql --user=root -p < schema.sql 
时报了错误：ERROR 1064 (42000) at line 15: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '{},
经验证，是schema.sql 文件中第17行代码导致的   ：round JSON default {},
我不懂sql语句，互联网也没有查到与之相关错误信息，请作者帮忙分析一下，谢谢。

**Comment by mailgyc** [comment]
应该是版本问题，试一下MySQL 8.0版本

On Jan 3, 2023, at 00:35, 劉清揚 ***@***.***> wrote:



你好作者，我在执行
mysql --user=root -p < schema.sql
时报了错误：ERROR 1064 (42000) at line 15: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '{},
经验证，是schema.sql 文件中第17行代码导致的 ：round JSON default {},
我不懂sql语句，互联网也没有查到与之相关错误信息，请作者帮忙分析一下，谢谢。

**Comment by wu5bocheng** [comment]
MySQL 5.7 introduced the JSON datatype, which matches your syntax.
