### ISSUE TITLE
Fail to install msgpack-python for python 3.6.0

### ISSUE THREAD

**Issue by godspeedgld** [mailgyc/doudizhu#4]
using pip3 install msgpack-python.

I get error:

Exception:
Traceback (most recent call last):
File "c:\users\godspeed\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat_init_.py", line 73, in console_to_str
return s.decode(sys.stdout.encoding)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 116: invalid start byte

During handling of the above exception, another exception occurred:

**Comment by mailgyc** [comment]
sorry, i don't know how to solve this, but it's easy to change send_message use json format.
